config/routes.rb
Rails.application.routes.draw do
  resources :posts

  root 'landing#home'

  get 'home' => 'landing#home'
  post 'home' => 'landing#home'


  get 'contact' => 'landing#contact'

  get 'about' => 'landing#about'

  # get 'blog' => 'landing#blog'

  get 'blog' => 'posts#index'

  get 'iot' => 'landing#iot'

  #get :send_contact_email, to: 'landing#send_contact_email', as: :send_contact_email

  post :send_contact_email, to: 'landing#send_contact_email', as: :send_contact_email


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(id: @comment.post_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :post_id)
    end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def home
    # ACTUAL LOCATION OF IP GEOLOOKUP - WILL ONLY WORK WHEN DEPOLYED
    @visitor_location = request.location.city

    # HARDCODED LOCATION FOR TESTING
    #@visitor_location = "Phoenix"

    response = HTTParty.get("http://api.apixu.com/v1/search.json?key=#{ENV['apixu_api_key']}&q=#{params[:city]}")
    response2 = HTTParty.get("http://api.apixu.com/v1/history.json?key=#{ENV['apixu_api_key']}&q=#{params[:city]}&dt=#{params[:date]}")

    if params[:city] != "" && params[:city] != nil
      if !response.blank?
        @lookup_location = response[0]['name']
      end
    end

    if params[:date] != "" && params[:date] != nil

      if !response2['error']
        @lookup_date = response2['forecast']['forecastday'][0]['date']
        @rails_json = response2
        @temp = []
        #@humidity = []
        for i in 0..23
          @temp[i] = response2['forecast']['forecastday'][0]['hour'][i]['temp_f']
          #@humidity[i] = response2['forecast']['forecastday'][0]['hour'][i]['humidity']
        end
      else
        render(
              html: "<script>
                    if(confirm('Please check your input.')) {
                      window.location.reload();
                      }
                    else {
                      window.location.reload();
                    }
                    </script>".html_safe,
              layout: 'application'
              )
      end
    end
  end

  def contact
  end

  def about
  end

  def blog
  end

  def iot
    @poll_time = Time.now.in_time_zone("Arizona").strftime("%I:%M:%S %p")



    downstairs_temp_array = HTTParty.get("http://blynk-cloud.com/#{ENV['blynk_downstairs_sensor_key']}/get/V1")
    downstairs_humidity_array = HTTParty.get("http://blynk-cloud.com/#{ENV['blynk_downstairs_sensor_key']}/get/V2")

    @downstairs_temp = downstairs_temp_array[0].to_f.round(2)
    @downstairs_humidity = downstairs_humidity_array[0].to_f.round(1)

    garage_status = HTTParty.get("http://blynk-cloud.com/#{ENV['blynk_garage_door_key']}/get/V1")

    if garage_status[0].to_i == 0
      @garagedoor = "Closed"
    else
      @garagedoor = "Open"
    end

    pool_temp_array = HTTParty.get("http://blynk-cloud.com/#{ENV['blynk_pool_temperature_key']}/get/V1")

    @pool_temperature = pool_temp_array[0]

  end


  def send_contact_email
    ContactMailer.contact_email(params[:name],params[:email],params[:phone],params[:subject],params[:message]).deliver_now
    redirect_to contact_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :author, :blog_entry)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
<% if comment.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(comment.errors.count, "error") %>
    prohibited this comment from being saved:</h2>

  <ul>
    <% comment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :author %>
  <%= form.text_field :author, id: :comment_author %>
</div>

<div class="field">
  <%= form.label :comment_entry %>
  <%= form.text_area :comment_entry, id: :comment_comment_entry %>
</div>

<div class="field">
  <%= form.hidden_field :post_id, value: @post.id %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment_entry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comment entry:</strong>
  <%= @comment.comment_entry %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/landing/about.html.erb
<body class="about_body">

  <div class="about_container">

    <div class="title"> Daniel Endres </div>

      <div class="skills_conatiner">

        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Programming Languages</h3>
          </div>
          <div class="panel-body">

            <div class="row">
                  <div class="col-xs-4 col-sm-2">
                    <a href="https://en.wikipedia.org/wiki/Java_(programming_language)" target="iframe0" id="myBtn0">
                    <i class="icon devicon-java-plain-wordmark"></i>
                    </a>
                  </div>
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-ruby-plain-wordmark"></i>
                  </div>
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-cplusplus-plain-wordmark"></i>
                  </div>
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-c-plain"></i>
                  </div>
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-python-plain-wordmark"></i>
                  </div>
                  <div class="col-xs-4 col-sm-2">

                  </div>
              </div>

          </div>
        </div>

        <div class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title">Web Development Skills</h3>
          </div>
          <div class="panel-body">

            <div class="row">
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-rails-plain-wordmark"></i>
                  </div>
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-html5-plain-wordmark"></i>
                  </div>
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-css3-plain-wordmark"></i>
                  </div>
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-javascript-plain"></i>
                  </div>
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-bootstrap-plain-wordmark"></i>
                  </div>
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-jquery-plain-wordmark"></i>
                  </div>
            </div>

          </div>
        </div>

        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title">Familiar with</h3>
          </div>
          <div class="panel-body">

            <div class="row">
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-git-plain-wordmark"></i>
                  </div>
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-github-plain-wordmark"></i>
                  </div>
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-heroku-original-wordmark"></i>
                  </div>
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-d3js-plain"></i>
                  </div>
                  <div class="col-xs-4 col-sm-2">
                  </div>
                  <div class="col-xs-4 col-sm-2">
                  </div>
            </div>


          </div>
        </div>


        <div class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title">Operating Systems</h3>
          </div>
          <div class="panel-body">
            <div class="row">
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-apple-original"></i>
                  </div>
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-windows8-original"></i>
                  </div>
                  <div class="col-xs-4 col-sm-2">
                    <i class="icon devicon-linux-plain"></i>
                  </div>
                  <div class="col-xs-4 col-sm-2">
                  </div>
                  <div class="col-xs-4 col-sm-2">
                  </div>
                  <div class="col-xs-4 col-sm-2">
                  </div>
            </div>

          </div>
        </div>

      </div>

  </div>




  <!-- TESTING MODAL / IFRAME -->

  <!-- The Modal -->
  <div id="myModal" class="modal">

    <!-- Modal content -->
    <div class="modal-content">
      <span class="close" title="Close">x</span>
      <iframe name="iframe0" width="95%" height="400px"></iframe>
    </div>

  </div>

  <script>
  // Get the modal
  var modal = document.getElementById('myModal');

  // Get the button that opens the modal
  var btn = document.getElementById("myBtn0");

  // Get the <span> element that closes the modal
  var span = document.getElementsByClassName("close")[0];

  // When the user clicks the button, open the modal
  btn.onclick = function() {
      modal.style.display = "block";
  }

  // When the user clicks on <span> (x), close the modal
  span.onclick = function() {
      modal.style.display = "none";
  }

  </script>

  <!-- END TESTING MODAL / IFRAME -->


</body>

app/views/landing/contact.html.erb
<body class="contact_body">

  <div class="contact_page">

    <div class="title">Contact Me</div>

      <div class="contact_form_container">

        <div class="form-area">

          <%= form_tag '/send_contact_email', method: 'post' do %>

            <br style="clear:both">

            <h3 style="margin-bottom: 25px; text-align: center;"> <i class="fa fa-envelope-o fa-border "></i> Send me a message</h3>

            <div class="form-group">
               <%= text_field_tag :name, nil, placeholder: "Name", :required => true, class: "form-control" %>
            </div>

            <div class="form-group">
               <%= email_field_tag :email, nil, placeholder: "E-mail", :required => true, class: "form-control" %>
            </div>

            <div class="form-group">
               <%= text_field_tag :phone, nil, placeholder: "Phone (optional)", class: "form-control" %>
            </div>

            <div class="form-group">
               <%= text_field_tag :subject, nil, placeholder: "Subject", :required => true, class: "form-control" %>
            </div>

            <div class="form-group">
               <%= text_area_tag :message, nil, :rows => 7, placeholder: "Message", :required => true, :maxlength => 350, id: "message", class: "form-control" %>
               <span class="help-block">
                 <p id="characterLeft" class="help-block ">...</p>
               </span>
            </div>

            <div class="actions">
              <%= submit_tag "Send Message", class: "btn btn-primary pull-right" %>
            </div>
          <% end %>
        </div>

      </div>
  </div>


  <script>
  $(document).ready(function(){
      $('#characterLeft').text('350 characters left');
      $('#message').keydown(function () {
          var max = 350;
          var len = $(this).val().length;
          if (len >= max) {
              $('#characterLeft').text('You have reached the limit');
              $('#characterLeft').addClass('red');
              $('#btnSubmit').addClass('disabled');
          }
          else {
              var ch = max - len;
              $('#characterLeft').text(ch + ' characters left');
              $('#btnSubmit').removeClass('disabled');
              $('#characterLeft').removeClass('red');
          }
      });
  });
  </script>

</body>

app/views/landing/home.html.erb
<body class="home_body">

  <div class="home_container">

    <div class="title">Weather Application</div>

    <div class="date_picker_container">
      <div class="row">
        <div class="col-md-12">
          <div class="well">
            <h2>Look Up Weather History</h2>
            <p>Pick a date for Weather history!</p>
            <div>
              <%= form_tag home_path do %>
              <div class="input-group">

                <div class="input-group">
                   <%= text_field_tag :city, @visitor_location, placeholder: "City", :required => true, class: "form-control" %>
                   <span class="input-group-addon">
                   <span class="glyphicon glyphicon-home"></span>
                </div>
                <div class='input-group date' id='datetimepicker5' >
                  <%= text_field_tag :date, nil, placeholder: "YYYY-MM-DD", :required => true, class: "form-control" %>
                  <span class="input-group-addon">
                  <span class="glyphicon glyphicon-calendar"></span>
               </div>
               <br/>
               <%= submit_tag "Show Temperature Graph", class: "btn btn-primary" %>
               <% end %>
             </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <% if @lookup_date != nil %>
    <div class="panel panel-default">
      <div class="chart">

      </div>
      <div class="panel-footer"> Temperatures in <%= @lookup_location %> on <%= @lookup_date %> </div>
    </div>
    <%end%>



    <script type="text/javascript">

    var startDate = moment().subtract(29, 'days').format('YYYY-MM-DD');
    var yesterdaysDate = moment().subtract(1, 'days').format('YYYY-MM-DD');

    $(function () {
        $('#datetimepicker5').datetimepicker({
            format: "YYYY-MM-DD",
            minDate: startDate,
            maxDate : 'now'
        });
    });

    </script>




    <script src="//d3js.org/d3.v3.min.js"></script>


    <script>

    //  var time = new Array();
    //  for (i = 0; i < 24; i++) {
        // format the time in 12 hr time format
    //    time = new Date(new Date().setHours(i, 0, 0)).toLocaleTimeString();
    //  }


      var temps = <%= @temp %>;

      var arrData = new Array();

      for (i = 0; i < 24; i++) {
        arrData.push([i , temps[i] ]);
        //arrData.push([time[i] , temps[i] ]);
      }



      // Set the dimensions of the canvas / graph
      var margin = {top: 30, right: 20, bottom: 30, left: 50},
        width = 600 - margin.left - margin.right,
        height = 270 - margin.top - margin.bottom;

      // Parse the date / time
      // var parseDate = d3.time.format("%d-%b-%y").parse;

      // Set the ranges
      //var x = d3.time.scale().range([0, width]);
      var x = d3.scale.linear().range([0, width]);

      var y = d3.scale.linear().range([height, 0]);

      // Define the axes
      var xAxis = d3.svg.axis().scale(x)
        .orient("bottom").ticks(0);

      var yAxis = d3.svg.axis().scale(y)
        .orient("left").ticks(5);

      // Define the line
      var valueline = d3.svg.line()
        .x(function(d) { return x(d.hour); })
        .y(function(d) { return y(d.temp); });

      // Adds the svg canvas
      var svg = d3.select(".chart")
          .append("svg")
              .attr("width", width + margin.left + margin.right)
              .attr("height", height + margin.top + margin.bottom)
          .append("g")
              .attr("transform",
                    "translate(" + margin.left + "," + margin.top + ")");

      // Get the data from csv
      // d3.csv("data.csv", function(error, data) {
      //     data.forEach(function(d) {
      //         d.hour = d.hour;
      //         d.temp = +d.temp;
      //     });

      // get Data from Array
      var data = arrData.map(function(d) {
          return {
             hour: d[0],
             temp: d[1]
          };

      });

      // Scale the range of the data
      x.domain(d3.extent(data, function(d) { return d.hour; }));
      y.domain([20, d3.max(data, function(d) { return d.temp; })]);
      //y.domain(d3.extent(data, function(d) { return d.temp; }));

      // Add the valueline path.
      svg.append("path")
          .attr("class", "line")
          .attr("d", valueline(data));

      // Add the X Axis
      svg.append("g")
          .attr("class", "x axis")
          .attr("transform", "translate(0," + height + ")")
          .call(xAxis);

      // Add the Y Axis
      svg.append("g")
          .attr("class", "y axis")
          .call(yAxis);

    </script>

  </div>

</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>danielendres.net</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.rawgit.com/konpa/devicon/df6431e323547add1b4cf45992913f15286456d3/devicon.min.css">

    <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">

  </head>

  <header>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Weather App</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <!-- <li><a href="/blog">Blog</a></li> -->
            <li><a href="/iot">Internet of Things</a></li>
            <!-- <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Separated link</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li> -->
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/about">About Me</a></li>
            <li><a href="/contact">Contact Me</a></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
  </header>

  <body>
    <%= yield %>

  </body>

  <footer class="footer navbar-inverse navbar-fixed-bottom text-center">
    <div class="container">
      <p>© 2017 Daniel Endres</p>
    </div>
  </footer>


</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :post_author %>
  </div>

  <div class="field">
    <%= form.label :blog_entry %>
    <%= form.text_area :blog_entry, id: :post_blog_entry %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<body class="blog_body">

  <p id="notice"><%= notice %></p>

  <div class="blog_page_contanier">

    <div class="blog_title">
      <h1>Blog Page</h1>
    </div>

    <div class="blog_posts_container">

      <% @posts.each do |post| %>
      <div class="blog_post">

        <div class="panel panel-default">
          <div class="panel-heading">
            <div class="blog_post_title panel-title"><%= post.title %></div>
            <div class="blog_post_author label label-default"><%= post.author %></div>
            <div class="blog_post_time label label-default pull-right"><%= post.created_at.strftime("%A, %d %b %Y at %l:%M %p") %></div>
          </div>
          <div class="panel-body">
            <div class="blog_post_entry"><%= post.blog_entry.html_safe %></div>
          </div>
          <div class="panel-footer">
            <%= link_to "Comment on this post", root_path, class: "btn btn-info" %>
            <%#= link_to "Show", post, class: "btn btn-info" %>
            <%#= link_to "Edit", edit_post_path(post), class: "btn btn-warning" %>
            <%#= link_to "Delete", post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>

            <span class="pull-right clickable">
              <i class="glyphicon glyphicon-chevron-up"></i>
            </span>
          </div>
          <div class="panel-body comments-body">
            <div class="blog_post_comment">comments will go here</div>
          </div>
        </div>

      </div>
      <% end %>
      <%= link_to 'New Blog Post', new_post_path, class: "btn btn-default btn-lg btn-block" %>

    </div>

  </div>

</body>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @post.author %>
</p>

<p>
  <strong>Blog entry:</strong>
  <%= @post.blog_entry.html_safe %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %>

<div id="comments">
  <%= render 'comments/form', comment: @comment %>

  <% @post.comments.each do |comment| %>
    <p>
      <%= comment.author %> said ... <br />
      <%= comment.comment_entry %>
    </p>
  <% end %>
</div>


<%= link_to 'Back', posts_path %>